### ISSUE TITLE
bug in DaemonUnit1.pas 

### ISSUE THREAD

**Issue by iotleaf** [arminlinder/Lazarus-FPC-Wiki-Code-Samples#2]
DaemonUnit1.pas

in..
`procedure TDaemon1.DataModuleStart`

This line is wrong..
`LogToFile(Format('Daemon %s received start signal, PID:%d', [GetProcessID]));`

.. and so prevents daemon from starting the worker thread..
See lazarus forum
https://forum.lazarus.freepascal.org/index.php/topic,62132.0.html

**Comment by arminlinder** [comment]
Thank you very much for bringing this glitch to my attention. Fixed.
